/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AButton: (typeof import('ant-design-vue/es'))['Button']
    ACheckboxGroup: (typeof import('ant-design-vue/es'))['CheckboxGroup']
    AConfigProvider: (typeof import('ant-design-vue/es'))['ConfigProvider']
    ADatePicker: (typeof import('ant-design-vue/es'))['DatePicker']
    AIcon: (typeof import('./components/global/AIcon.vue'))['default']
    AInput: (typeof import('ant-design-vue/es'))['Input']
    AInputSearch: (typeof import('ant-design-vue/es'))['InputSearch']
    APagination: (typeof import('ant-design-vue/es'))['Pagination']
    ARadioButton: (typeof import('ant-design-vue/es'))['RadioButton']
    ARadioGroup: (typeof import('ant-design-vue/es'))['RadioGroup']
    ASwitch: (typeof import('ant-design-vue/es'))['Switch']
    ATabPane: (typeof import('ant-design-vue/es'))['TabPane']
    ATabs: (typeof import('ant-design-vue/es'))['Tabs']
    ElButton: (typeof import('element-plus/es'))['ElButton']
    ElCheckbox: (typeof import('element-plus/es'))['ElCheckbox']
    ElColorPicker: (typeof import('element-plus/es'))['ElColorPicker']
    ElSlider: (typeof import('element-plus/es'))['ElSlider']
    GlobalCmp: (typeof import('./components/global/GlobalCmp.vue'))['default']
    IconFont: (typeof import('./components/global/IconFont.vue'))['default']
    VanNavBar: (typeof import('vant/es'))['NavBar']
    VanNumberKeyboard: (typeof import('vant/es'))['NumberKeyboard']
    VanTabbar: (typeof import('vant/es'))['Tabbar']
    VanTabbarItem: (typeof import('vant/es'))['TabbarItem']
  }
}
